### ISSUE TITLE
启停工具，如果退出忘了点停止，下次可能就无法启动

### ISSUE THREAD

**Issue by q791014690** [SleepNap/NapMysqlTool#1]
启停工具，如果退出忘了点停止，下次可能就无法启动

**Comment by SleepNap** [comment]
未停止mysql的情况下直接关机，下次开机无法启动的情况。
扩展启停工具的修复功能修复该情况，如无法启动点击修复即可。

**Comment by SleepNap** [comment]
等下版本发布

**Comment by SleepNap** [comment]
https://github.com/SleepNap/NapMysqlTool/releases/tag/1.24.1028
